Almost entirely rewrite scr to be POSIX compliant
However, it is unfortunately untested for now

- No more reliance on bash arrays (or other bashisms)
- Can no longer accept the session name (a positional argument) until
  after all other arguments have been passed
- Was able to retain the -- argument to pass all subsequent arguments
  to SSH directly
- Enable debugging mode based on an environment variable

diff --git a/opt/bin/scr b/opt/bin/scr
--- a/opt/bin/scr
+++ b/opt/bin/scr
@@ -1,109 +1,108 @@
-#!/bin/bash
+#!/bin/sh
 
-# set -e
-# set -u
+set -e
+
+if test $SCRDEBUG; then
+    debugprint() { echo "DEBUG: $@"; }
+    set -x
+else
+    debugprint() { true; }
+fi
+
+set -u
+
+debugprint "Debugging enabled"
 
 usage() {
-    echo "scr() [-h|--help] [-r|--remote <REMOTE HOST>] [-d|--debug] "
-    echo "      [SESSION NAME] [-- <SSH ARGUMENTS>]"
-    echo ""
-    echo "Screen session management wrapper"
-    echo "Attach to session if it exists, otherwise create a new one"
-    echo ""
-    echo "    -r <REMOTE HOST>: connect to a screen session on a remote host."
-    echo "    -d: Print debug messages (probably useless)."
-    echo "    -h: Print help and exit."
-    echo "    SESSION NAME: provide an optional session name. Default is 'camelot'."
-    echo "        It is recommended to use the default until you need more than one"
-    echo "        session on a given host."
-    echo "    --: Indicates that all remaining arguments should be passed to ssh."
-    echo "        For example: scr -r example.com -- -i ~/.ssh/special_id_rsa"
+    cat <<ENDUSAGE
+scr() [-h|--help] [-r|--remote <REMOTE HOST>] [-w|--whatif]
+      [SESSION NAME] [-- <SSH ARGUMENTS>]
+
+Screen session management wrapper
+Attach to session if it exists, otherwise create a new one
+
+ARGUMENTS
+    -h: Print help and exit.
+    -r <REMOTE HOST>: connect to a screen session on a remote host.
+    -w: Do not actually execute screen or ssh
+    SESSION NAME: provide an optional session name. Default is 'camelot'.
+        It is recommended to use the default until you need more than one
+        session on a given host.
+    --: Indicates that all remaining arguments should be passed to ssh.
+        For example: scr -r example.com -- -i ~/.ssh/special_id_rsa
+
+ENVIRONMENT
+    SCRDEBUG: If set, print debugging messages
+ENDUSAGE
 }
 
-i=0
-pctr=0
-argcount=$#
-posargs=()
-remote=false
+actr=0
+remote=
+whatif=
+fallbacksessionname=SCRSESSION
+sessionname=
+sshargs=
+remainingsshargs=
 
-# These functions are redefined if debug mode is turned on
-#execute the arguments directly (normal mode; will change this in debug mode)
-ee(){ $*; }
-#noop; totally ignore arguments.
-debugprint() { true; }
-
-while [ $i -lt $argcount ]; do
+while test $actr -lt $#; do
     debugprint "Processing argument '$1'..."
     case "$1" in
+        -h | --help ) usage; exit 0;;
         -r | --remote )
-            # increment i twice because we are eating 2 arguments
-            remote=true; rhost=$2; ((i+=2)); shift 2;;
-        -d | --debug )
-            set -x
-            # don't execute, just print
-            ee() { echo $*; }
-            # print debug statements too
-            debugprint() { echo $*; }
-            debugprint "Debuggin'"
+            remote=1; rhost=$2; actr=$((actr+=2)); shift 2;;
+        -w | --whatif )
+            whatif=1
+            actr=$((atr+=1))
             shift;;
-        -h | --help ) usage; return ;;
         --)
-            declare -a sa
-            sctr=0
-            shift
-            while [ $i -lt $argcount ]; do
-                sa[$sctr]=$1
-                ((sctr++))
-                ((i++))
-                shift
-            done
-            ;;
+            debugprint "Found -- argument, passing remaining arguments to SSH"
+            remainingsshargs=1; shift; actr=$((actr+=1)); break;;
         *)
-            [ $1 ] && if [ ${1:0:1} == "-" ]; then 
-                echo "Error: you supplied option '$1', but there is no such option"
-                scr_help
-                return
+            if test "$remainingsshargs"; then
+                sshargs="${sshargs} \"$1\""
+            elif test $(echo $1 | cut -c1) = "-"; then
+                echo "Error: Supplied invalid option '$1' (and the -- argument was not present to indicate that '$1' should be passed to SSH)"
+                usage
+                exit 1
+            elif test "$sessionname"; then
+                echo "Error: Supplied positional argument '$1', but had already passed a positional argument '$sessionname' (and the -- argument was not present to indicate that '$1' should be passed to SSH"
+                usage
+                exit 1
+            else
+                sessionname=$1
             fi
-            posargs[pctr]=$1; ((pctr++)); ((i++)); 
-            shift;;
+            actr=$((actr+=1)); shift;;
     esac
 done
 
-if [ $pctr -gt 1 ]; then
-    echo "Error: you supplied too many positional arguments"
-    usage
-    return
-elif [ $posargs ]; then
-    sessionname=$posargs #posargs will never have more than 1 so this is safe in this function
-elif [ $default_session_name ]; then
-    sessionname="${default_session_name}"
-else
-    sessionname="fallback"
+if test -z "$sessionname"; then
+    if test "$default_session_name"; then
+        sessionname="$default_session_name"
+    else
+        sessionname="$fallbacksessionname"
+    fi
 fi
 debugprint "Session name: $sessionname"
 
 # if you're in a screen session and creating a new one, use a different escape key (handy)
-if [[ $TERM == "screen" ]]; then
+if test $TERM = "screen"; then
     # -e :: changes the screen escape key. NOT set in .screenrc! otherwise that *sometimes* overrides cli option (bug?)
     scrargs="-e^]]"
-    debugprint "Running inside a screen session, going to use srcargs: ${srcargs}"
 else
     scrargs="-e^tt"
-    debugprint "Not running inside screen, going to use srcargs: ${srcargs}"
 fi
-
-sshargs=" "
-if $sa; then
-    i=0
-    while [ $i -lt ${#sa} ]; do
-        sshargs+=" ${sshargs[$i]}"
-        ((i++))
-    done
-fi
+debugprint "Using scrargs: ${scrargs}"
 
 screen_call="screen $scrargs -D -R -S $sessionname"
-if $remote; then
-    ee ssh $sshargs -t $rhost "$screen_call"
+debugprint "Calling screen like: $screen_call"
+if test $remote; then
+    debugprint ssh $sshargs -t $rhost "$screen_call"
+    if test ! $whatif; then
+        ssh $sshargs -t $rhost "$screen_call"
+    fi
 else
-    ee $screen_call
+    debugprint $screen_call
+    if test ! $whatif; then
+        $screen_call
+    fi
 fi
