OpenVPN server is starting, but not routing iPhone traffic
Status:

- iPhone with (previously generated) config can connect but not use the
  Internet once connected
- haven't tried anything else

OpenVPN changes:

- use single server.ovpn file with all keys and certs inside it
- fix some broken unpriv stuff
- HOWEVER, unpriv is still a work in progress
- in "run" sh script, redirect all stdout/stderr to log
- don't push redirect-gateway, let the client do so if it wants
  (required for future hardened Linux VPN clients)

Non OpenVPN stuff (that was necessary to make this work)

- use a local volume for the docker registry server
- moved different vars/tasks/whatever around to their proper place
- break out site.yml into different sub config files
- use an inventory/ directory for inventory files

diff --git a/ansible/roles/openvpn-docker-builder/files/run b/ansible/roles/openvpn-docker-builder/files/run
--- a/ansible/roles/openvpn-docker-builder/files/run
+++ b/ansible/roles/openvpn-docker-builder/files/run
@@ -1,27 +1,55 @@
-#!/bin/sh
-set -eu
+#!/bin/bash
+#set -eu
+
+OVPNDIR="/etc/openvpn"
+
+touch /etc/openvpn/docker-run.log
+exec 3>&1 4>&2 >/etc/openvpn/docker-run.log 2>&1
+
+log() {
+    date=`date --rfc-3339=seconds`
+    message="$date $*"
+    echo "$message"
+}
 
 # NOTE: Older instructions will tell you to "modprobe tun" before running the 
 # openvpn --mktun command. For newer kernels, tun support appears to be built 
 # in, meaning modprobe won't work but this will:
-[ -d /dev/net ]     || mkdir -p /dev/net
-[ -c /dev/net/tun ] || mknod /dev/net/tun c 10 200
+if [ -d /dev/net ]; then 
+    log "/dev/net exists"
+else 
+    log "Creating /dev/net directory"
+    mkdir -p /dev/net
+fi
+if [ -c /dev/net/tun ]; then
+    log "/dev/net/tun already exists"
+else
+    log "Creating /dev/net/tun with mknod"
+    mknod /dev/net/tun c 10 200
+fi
+
+log "Using OpenVPN to make the tun1194 device"
 openvpn --mktun --dev tun1194 --dev-type tun --user openvpn --group openvpn
 
 cd /etc/openvpn
-for file in server.ovpn dh.pem vpnserver.crt vpnserver.key ca.crt ta.key; do
-    [ -f "$file" ] || {
-        echo "The \"$file\" file is missing from your /etc/openvpn volume"
-        exit 1
-    }
-done
-chown -R openvpn:openvpn .
+[ -f server.ovpn ] || {
+    echo "The \"$file\" file is missing from your \"/etc/openvpn\" volume"
+    exit 1
+}
+#chown -R openvpn:openvpn .
 
 #sysctl -w net.ipv4.ip_forward=1
+log "Using OpenVPN to make the tun1194 device"
 iptables -t nat -A POSTROUTING -s {{ openvpn_private_subnet }}/24 -o eth0 -j MASQUERADE
 
+log "Creating the OpenVPN server log"
 touch openvpn-server.log
+log "Starting OpenVPN..."
+
+# Undo the output redirection:
+exec 1>&3 2>&4
+
+openvpn server.ovpn | tee --append openvpn-server.log 
 #while true ; do openvpn server.ovpn ; done >> openvpn-server.log &
 #su -c "openvpn server.ovpn" - openvpn | tee --append openvpn-server.log 
-openvpn server.ovpn | tee --append openvpn-server.log 
 
